root = global ? window

root.mkCsv = (eid) ->
  exp = Experiments.findOne eid
  return null unless exp
  runs = getExpRuns(eid).fetch()

  data = getTableData(exp, runs, [], []);
  cols = colNames(runs);
  d2 = addHeaderCells(data, colNames(runs), rowNames2(exp));
  console.log(data, d2);
  str = arrayToCsv(d2)

#  sids = ExpRuns.find({exp: eid}).map((r) ->_.map(r.samples,(v) -> v))
  sids = _.flatten(ExpRuns.find({exp: eid}).map((r) ->_.map(r.samples,(v) -> {sample: v, run: r._id})))

  s_str = arrayToCsv(
    _.map sids, (ss) ->
      s = Samples.findOne(ss.sample)
      [s.name, ss.run, s._id, moment(s.timestamp).format('M/D/YYYY'), s.note]
  )


  'Generated by https://labnote.meteor.com/' + '\r\n' +
  'Experiment,' + exp.name + ',' + moment(exp.date).format('M/D/YYYY') + '\r\n' +
  'Exported time,' + moment().format('M/D/YYYY HH:mm:ss') + '\r\n' +
  (if exp.locked then 'Experiment finished (data frozen)' else '') +
  '''
  Samples\r\n''' +
  s_str +
  '''\r\n
  'Steps\r\n''' +
  str

root.arrayToCsv = (xss) ->
  (_.map xss, (xs) ->
    (_.map xs, (x) ->
      innerValue = x?.toString() || ''
      result = innerValue.replace(/"/g, '""')
      if result.search /("|,|\n)/g >= 0
        result = '"' + result + '"'
      result).join(',') + '\r\n').join('')


# PDF export
root.mkPdf = (exp) ->
  doc = new jsPDF()

  doc.setFont("helvetica");
  doc.setFontType("bold");
  doc.setFontSize(20)
  doc.text(20, 20, exp.name);

  doc.setFont("helvetica");
  doc.setFontType("normal");
  doc.setFontSize(12)
  doc.text(20, 30, 'Date: ' + moment(exp.date).format('M/D/YYYY'));

  doc.setFont("helvetica");
  doc.setFontType("normal");
  doc.setFontSize(12)
  doc.text(20, 50, 'Samples');

  str = doc.output 'datauristring', {}
  window.open(str)


root.getSpreadsheetUrl = (id) -> 'https://drive.google.com/spreadsheets/d/' + id
